@baseUrl = http://localhost:5085

Get {{baseUrl}}/login?firstApi=true
Accept: application/json

###
GET {{baseUrl}}/WeatherForecast/PP/weatherforecast
Accept: application/json
Authorization: Bearer CfDJ8DlGRX4W319GqrvHY04EhmwfXcREHhUgR-_AyBFJMH9SY1rxVd-ylrdkG4jyp4nlteUeP72XadSEewX-0g212NxcuuwB4igAOSlriaSfb_YglDbn2OPaaFRSG9C9AzBaGZg-e7Mb1d4UXv5sWy52I6SnIJwEra7MWuLTAw76Wbd_kPeWxhvWC-5lGBcmpKq-OmQUSCcBRvrffEVU2O75CRv2LdrVErscifYQbCWkdE3p7J4BwvngH20IqVczrOPxEuYJzroap53-R2KuIPN1wZV_fCY2VGWXIz_zyCP6R9tyoif7qgX4lFyDswVySmrLClyBjaX8MNW5YMi5jLPR-EPdYe_Kn1_3RHdxpI-qBEOZ

###

POST {{baseUrl}}/weatherservice/weatherforecast
Accept: application/json
Content-Type: application/json

{
    "guid": "95ff2229-788a-4c51-a4aa-ac75fddf2395",
    "date": "2024-12-03",
    "temperatureC": 14,
    "summary": "Tes51"
  }
